version: "3"

volumes:
  teamspeak:
  mariadb:

services:
  teamspeak:
    image: teamspeak
    restart: always
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      - TS3SERVER_DB_PLUGIN=ts3db_mariadb
      - TS3SERVER_DB_SQLCREATEPATH=create_mariadb
      - TS3SERVER_DB_HOST=mariadb
      - TS3SERVER_DB_USER=root
      - TS3SERVER_DB_PASSWORD=
      - TS3SERVER_DB_NAME=teamspeak
      - TS3SERVER_DB_WAITUNTILREADY=30
      - TS3SERVER_LICENSE=accept
    volumes:
      - teamspeak:/var/ts3server

  mariadb:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=teamspeak
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mariadb:/var/lib/mysql
