version: "3"

networks:
  proxy:
    external: true

volumes:
  mariadb:

services:
  nextcloud:
    image: nextcloud:latest
    restart: always
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - MYSQL_HOST=mariadb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
    networks:
      - default
      - proxy
    volumes:
      - ${LOCAL_DIRECTORY}:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - default
    volumes:
      - mariadb:/var/lib/mysql
