version: "3"

networks:
  proxy:
    external: true

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - |
        GITLAB_OMNIBUS_CONFIG=
        external_url '${EXTERNAL_URL}'
        gitlab_rails['lfs_enabled'] = true
        gitlab_rails['initial_root_password'] = 'password'
        gitlab_rails['gitlab_default_theme'] = 2
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
    ports:
      - "22:22"
    networks:
      - default
      - proxy
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
