version: "3"

networks:
  proxy:
    external: true

services:
  ghost:
    image: ghost:latest
    restart: always
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=2368
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - database__client=mysql
      - database__connection__host=mysql
      - database__connection__user=root
      - database__connection__password=
      - database__connection__database=ghost
      - url=${PUBLIC_URL}
    networks:
      - default
      - proxy
    volumes:
      - ./data/ghost:/var/lib/ghost/content
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=ghost
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - default
    volumes:
      - ./data/mysql:/var/lib/mysql
