version: "3"

networks:
  proxy:
    external: true

services:
  matomo:
    image: matomo:latest
    restart: always
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - MATOMO_DATABASE_HOST=mysql
      - MATOMO_DATABASE_USERNAME=root
      - MATOMO_DATABASE_PASSWORD=
      - MATOMO_DATABASE_DBNAME=matomo
    networks:
      - default
      - proxy
    volumes:
      - ./data/matomo:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=matomo
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - default
    volumes:
      - ./data/mysql:/var/lib/mysql
