version: "3"

networks:
  proxy:
    external: true

volumes:
  matomo:
  mysql:

services:
  matomo:
    image: matomo:latest
    restart: always
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - MATOMO_DATABASE_HOST=mysql
      - MATOMO_DATABASE_USERNAME=root
      - MATOMO_DATABASE_PASSWORD=
      - MATOMO_DATABASE_DBNAME=matomo
    networks:
      - default
      - proxy
    volumes:
      - matomo:/var/www/html
    depends_on:
      - mysql

  matomo-cron:
    image: matomo:latest
    restart: always
    volumes:
      - matomo:/var/www/html
    depends_on:
      - matomo
      - mysql
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      while /bin/true; do
      su -s "/bin/bash" -c "/usr/local/bin/php /var/www/html/console core:archive" www-data
      sleep 900
      done
      EOF'

  mysql:
    image: mysql:5.7
    restart: always
    command: --max_allowed_packet=64M
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=matomo
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - default
    volumes:
      - mysql:/var/lib/mysql
